// <auto-generated />
namespace Obads2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class gendercolumnadded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(gendercolumnadded));
        
        string IMigrationMetadata.Id
        {
            get { return "202009192317536_gender-column-added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
